language: go
go:
  - "1.14.x"

os:
  - linux

services:
  - docker

env:
  - GO111MODULE=on

script:
  - go test -v ./...
  - docker build -f Dockerfile-udigd -t mkmik/udigd .

deploy:
  provider: script
  script: >-
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin;
    docker push mkmik/udigd
  on:
    branch: master
