language: go
go:
  - "1.11.x"

os:
  - linux

services:
  - docker

env:
  - GO111MODULE=on

script:
  - go build ./...
  - go test -v ./...
  - docker build -f Dockerfile-udigd -t mkmik/udigd .

deploy:
  provider: script
  script: |
    echo Pushing image to docker
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    docker push mkmik/udigd
  on:
    branch: master
