language: go
go:
  - "1.11.x"

os:
  - linux

services:
  - docker

env:
  - GO111MODULE=on

install:
  - echo vendored deps

script:
  - go build -mod=vendor ./...
  - go test -v -mod=vendor ./...
  - docker build -f Dockerfile-udigd -t mkmik/udigd .

deploy:
  provider: script
  script: >-
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin;
    docker push mkmik/udigd
  on:
    branch: master
