language: go
go:
  - "1.11.x"
  - master

os:
  - linux

services:
  - docker

env:
  - GO111MODULE=on

script:
  - go build ./...
  - go test -v ./...
  - docker build -f Dockerfile-udigd -t mkmik/udigd .
